openapi: 3.0.0
info:
  title: Simulador de Exchange
  description: API para simular operaciones de compra/venta de criptomonedas.
  version: "1.0.0"
  contact:
    name: Tu Nombre
    email: tunombre@email.com

servers:
  - url: http://localhost:5000
    description: Servidor local

paths:
  /:
    get:
      summary: P치gina principal
      responses:
        '200':
          description: P치gina principal renderizada

  /trading:
    get:
      summary: Muestra la interfaz de trading
      responses:
        '200':
          description: P치gina de trading renderizada
    post:
      summary: Procesa una operaci칩n de compra o venta
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                tipo:
                  type: string
                  example: "compra"
                ticker:
                  type: string
                  example: "BTC"
                cantidad:
                  type: string
                  example: "0.1"
      responses:
        '302':
          description: Redirecciona con resultado

  /billetera:
    get:
      summary: Vista HTML con el estado de la billetera
      responses:
        '200':
          description: Renderiza billetera.html

  /estado:
    get:
      summary: Devuelve el estado actual de la billetera en JSON
      responses:
        '200':
          description: Datos de billetera

  /api/billetera:
    get:
      summary: Fragmento HTML con detalle financiero
      responses:
        '200':
          description: Fragmento HTML generado

  /api/historial:
    get:
      summary: Fragmento HTML del historial de transacciones
      responses:
        '200':
          description: Historial renderizado

  /actualizar:
    get:
      summary: Actualiza las cotizaciones desde CoinGecko
      responses:
        '200':
          description: Devuelve estado y cantidad

  /datos_tabla:
    get:
      summary: Devuelve fragmento de tabla de cotizaciones
      responses:
        '200':
          description: Tabla HTML renderizada

  /api/velas:
    get:
      summary: Retorna los datos de velas desde archivo local
      responses:
        '200':
          description: JSON de velas
        '500':
          description: Error de lectura